#!/usr/bin/env bash
# Script that configures /etc/hosts so that:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cat <<EOF | sudo tee /etc/hosts > /dev/null
127.0.0.1   ubuntu
127.0.0.2   localhost
8.8.8.8     facebook.com
EOF
