#!/usr/bin/env bash
# Script that configures /etc/hosts so that:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

# Ici on utilise une redirection par bloc (heredoc) avec 'cat <<EOF'
# Tout ce qui se trouve entre 'EOF' et 'EOF' sera envoyé à la commande suivante.

cat <<EOF | sudo tee /etc/hosts > /dev/null
127.0.0.1   ubuntu
127.0.0.2   localhost
8.8.8.8     facebook.com
EOF

# 127.0.0.1 Ubuntu -		Associe l’adresse 127.0.0.1 au nom 'ubuntu' (ou autre hostname du système)
# 127.0.0.2 localhost -		Redéfinit 'localhost' pour qu’il pointe vers 127.0.0.2 (comme demandé)
# 8.8.8.8 facebook.com	-	Fait en sorte que 'facebook.com' résolve vers 8.8.8.8


# Explication de la ligne :
# - 'cat <<EOF' génère le bloc de texte.
# - Ce bloc est passé à 'sudo tee /etc/hosts' qui écrit dans /etc/hosts (avec droits root).
# - '> /dev/null' empêche tee d’afficher le contenu du fichier dans le terminal.
